
class BasesDeDatos():
    DB_PRINCIPAL = 'db_principal'

class AreasProduccion():
    EXTRUSION = 'EXTRUSION'
    CARGUE_VAGONETAS = 'CARGUE DE VAGONETAS'
    DESCARGUE_VAGONETAS = 'DESCARGUE DE VAGONETAS'
    #COCCION = 'COCCION'
    COCHADO = 'COCHADO'
    DESPACHOS = 'DESPACHOS'


    list_areas_produccion = [EXTRUSION, CARGUE_VAGONETAS, DESCARGUE_VAGONETAS, COCHADO, DESPACHOS]